# Generated by Django 5.0.6 on 2024-06-17 00:33

import django.core.validators
import django.db.models.deletion
import web_MangaC.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Anonimo', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='tabla_capitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.FileField(blank=True, null=True, upload_to=web_MangaC.models.obtener_ruta_subida)),
                ('num_capitulo', models.PositiveSmallIntegerField(verbose_name='Número de Capitulo')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('Fech_upload', models.DateField(auto_now=True, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['manga', 'num_capitulo'],
            },
        ),
        migrations.CreateModel(
            name='tabla_generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='tabla_historial_lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fech_lectura', models.DateField(auto_now_add=True, verbose_name='Fecha de lectura')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_capitulos')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Lectura',
                'verbose_name_plural': 'Historial de Lectura',
            },
        ),
        migrations.CreateModel(
            name='tabla_mangas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fech_publicacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Fecha de Publicación')),
                ('estado', models.CharField(choices=[('Emision', 'Emisión'), ('Pausa', 'Pausa'), ('Finalizado', 'Finalizado')], max_length=10)),
                ('portada', models.ImageField(null=True, upload_to='portadas/')),
                ('descripcion', models.TextField(null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_autores')),
                ('genero_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_generos', verbose_name='Genero Principal')),
                ('subgenero', models.ManyToManyField(blank=True, related_name='sub_mangas_set', to='web_MangaC.tabla_generos', verbose_name='Subgenero')),
            ],
            options={
                'verbose_name': 'Manga/Comic',
                'verbose_name_plural': 'Manga/Comic',
            },
        ),
        migrations.AddField(
            model_name='tabla_capitulos',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_mangas'),
        ),
    ]
