# Generated by Django 5.0.6 on 2024-05-11 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='tabla_capitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_capitulo', models.IntegerField(verbose_name='Numero de capitulo')),
                ('Fech_publicacion', models.DateField(auto_now=True, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
            },
        ),
        migrations.CreateModel(
            name='tabla_generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='tabla_contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ImageField(upload_to='')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_capitulos')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='tabla_historial_lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_lectura', models.DateField(auto_now_add=True, verbose_name='Fecha de lectura')),
                ('Capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_capitulos')),
                ('ID_Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Lectura',
                'verbose_name_plural': 'Historial de Lectura',
            },
        ),
        migrations.CreateModel(
            name='tabla_manga_comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Fech_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('Estado', models.CharField(max_length=20)),
                ('Descripcion', models.TextField(null=True)),
                ('Autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_autores')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_generos')),
            ],
            options={
                'verbose_name': 'Manga/Comic',
                'verbose_name_plural': 'Manga/Comic',
            },
        ),
        migrations.AddField(
            model_name='tabla_capitulos',
            name='Manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_manga_comic'),
        ),
    ]
