# Generated by Django 5.0.6 on 2024-06-01 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla_mangas',
            name='Genero',
        ),
        migrations.AddField(
            model_name='tabla_mangas',
            name='GeneroPrincipal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_generos'),
        ),
        migrations.AddField(
            model_name='tabla_mangas',
            name='Subgenero',
            field=models.ManyToManyField(blank=True, related_name='sub_mangas_set', to='web_MangaC.tabla_generos'),
        ),
    ]
