# Generated by Django 5.0.6 on 2024-05-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_capitulos',
            name='titulo',
            field=models.CharField(default='[titulo]', max_length=100),
        ),
    ]
