# Generated by Django 5.0.6 on 2024-06-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0002_remove_tabla_mangas_genero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabla_capitulos',
            options={'ordering': ['manga', 'num_capitulo'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.RenameField(
            model_name='tabla_capitulos',
            old_name='Manga',
            new_name='manga',
        ),
        migrations.RenameField(
            model_name='tabla_capitulos',
            old_name='Num_capitulo',
            new_name='num_capitulo',
        ),
        migrations.RenameField(
            model_name='tabla_historial_lectura',
            old_name='Capitulo',
            new_name='capitulo',
        ),
        migrations.RenameField(
            model_name='tabla_historial_lectura',
            old_name='Fecha_de_lectura',
            new_name='fech_lectura',
        ),
        migrations.RenameField(
            model_name='tabla_historial_lectura',
            old_name='ID_Usuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='tabla_mangas',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='tabla_mangas',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tabla_mangas',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='tabla_mangas',
            old_name='Fech_publicacion',
            new_name='fech_publicacion',
        ),
        migrations.RenameField(
            model_name='tabla_mangas',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tabla_mangas',
            old_name='Portada',
            new_name='portada',
        ),
        migrations.RemoveField(
            model_name='tabla_autores',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='tabla_autores',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='tabla_capitulos',
            name='Detalle',
        ),
        migrations.RemoveField(
            model_name='tabla_capitulos',
            name='Titulo',
        ),
        migrations.RemoveField(
            model_name='tabla_generos',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='tabla_generos',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='tabla_mangas',
            name='GeneroPrincipal',
        ),
        migrations.RemoveField(
            model_name='tabla_mangas',
            name='Subgenero',
        ),
        migrations.AddField(
            model_name='tabla_mangas',
            name='genero_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_generos', verbose_name='Genero Principal'),
        ),
        migrations.AddField(
            model_name='tabla_autores',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='tabla_autores',
            name='nombre',
            field=models.CharField(default='Anonimo', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='tabla_capitulos',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabla_generos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='tabla_generos',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='tabla_mangas',
            name='subgenero',
            field=models.ManyToManyField(blank=True, related_name='sub_mangas_set', to='web_MangaC.tabla_generos', verbose_name='Subgenero'),
        ),
    ]
