# Generated by Django 5.0.6 on 2024-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0002_tabla_capitulos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_contenido',
            name='detalle',
            field=models.CharField(default='[num_img]', max_length=10),
        ),
    ]
