# Generated by Django 5.0.6 on 2024-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0003_tabla_contenido_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_contenido',
            name='contenido',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tabla_contenido',
            name='detalle',
            field=models.CharField(default='[doc_name]', max_length=30),
        ),
    ]
