# Generated by Django 5.0.6 on 2024-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0004_alter_tabla_contenido_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_contenido',
            name='contenido',
            field=models.FileField(upload_to='Mairimashita!_Iruma-kun'),
        ),
    ]
