# Generated by Django 5.0.6 on 2024-05-21 02:03

import django.db.models.deletion
import web_MangaC.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_MangaC', '0005_alter_tabla_contenido_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabla_capitulos',
            options={'ordering': ['Manga', 'Num_capitulo'], 'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
        migrations.RemoveField(
            model_name='tabla_capitulos',
            name='titulo',
        ),
        migrations.AddField(
            model_name='tabla_capitulos',
            name='Detalle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tabla_capitulos',
            name='capitulo',
            field=models.FileField(null=True, upload_to=web_MangaC.models.obtener_ruta_subida),
        ),
        migrations.AddField(
            model_name='tabla_manga_comic',
            name='Portada',
            field=models.ImageField(null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='tabla_capitulos',
            name='Num_capitulo',
            field=models.PositiveSmallIntegerField(verbose_name='Número de Capitulo'),
        ),
        migrations.AlterField(
            model_name='tabla_manga_comic',
            name='Autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_MangaC.tabla_autores'),
        ),
        migrations.AlterField(
            model_name='tabla_manga_comic',
            name='Estado',
            field=models.CharField(blank=True, choices=[('Emision', 'Emisión'), ('Pausa', 'Pausa'), ('Finalizado', 'Finalizado')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='tabla_manga_comic',
            name='Genero',
        ),
        migrations.DeleteModel(
            name='tabla_contenido',
        ),
        migrations.AddField(
            model_name='tabla_capitulos',
            name='Titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabla_manga_comic',
            name='Genero',
            field=models.ManyToManyField(to='web_MangaC.tabla_generos'),
        ),
    ]
